/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Accumulated state for one CF solve phase, included in solved/failed events. This is the single source of truth — TypeScript and Python types are generated from this schema.
 */
export interface CloudflareSnapshot {
  /**
   * How CF was detected: cf_chl_opt, title_interstitial, challenge_element, etc.
   */
  detection_method?: string | null;
  /**
   * Cloudflare Ray ID from _cf_chl_opt.cRay
   */
  cf_cray?: string | null;
  /**
   * Number of 500ms polls before challenge detected (1-20)
   */
  detection_poll_count?: number;
  /**
   * Whether the CF solver found the Turnstile widget element
   */
  widget_found?: boolean;
  /**
   * Which method found the widget: iframe-src, shadow-root-div, etc.
   */
  widget_find_method?: string | null;
  /**
   * All widget find methods tried across retries
   */
  widget_find_methods?: string[];
  /**
   * Click target X coordinate
   */
  widget_x?: number | null;
  /**
   * Click target Y coordinate
   */
  widget_y?: number | null;
  /**
   * Whether the CF solver's click caused the solve. False if CF auto-solved independently. See click_attempted for dispatch-level tracking.
   */
  clicked?: boolean;
  /**
   * Whether the CF solver dispatched a click (regardless of outcome). Use for diagnostics. For attribution, use 'clicked' which indicates the click caused the solve.
   */
  click_attempted?: boolean;
  /**
   * Number of times the widget was clicked
   */
  click_count?: number;
  /**
   * Actual click X coordinate (after mouse approach)
   */
  click_x?: number | null;
  /**
   * Actual click Y coordinate
   */
  click_y?: number | null;
  /**
   * Human presence simulation duration in ms
   */
  presence_duration_ms?: number;
  /**
   * Number of presence phases (>1 if retried)
   */
  presence_phases?: number;
  /**
   * Number of approach phases (0 = auto-solved before approach)
   */
  approach_phases?: number;
  /**
   * Activity loop iterations (each 3-7s)
   */
  activity_poll_count?: number;
  /**
   * False positive solve detections
   */
  false_positive_count?: number;
  /**
   * Widget error state detections
   */
  widget_error_count?: number;
  /**
   * Turnstile iframe state sequence: verifying, success, fail, etc.
   */
  iframe_states?: string[];
  /**
   * JSON debug info from click target search (iframes, ts_els, forms, shadow_hosts)
   */
  widget_find_debug?: {
    [k: string]: unknown;
  } | null;
  /**
   * Last error type: confirmed_error, error_text, iframe_error, expired
   */
  widget_error_type?: string | null;
}
