# Ignore non-webkit routes
src/routes/chrome
src/routes/chromium
src/routes/firefox
src/routes/edge

# Build Files
node_modules/
build/

# Editor preferences
.editorconfig
.dockerignore
.git/
.no-git/
.vscode/

# ENV files
*.env*

# Other non-production dotfiles
.eslintrc
