name: Backwards Compatibility

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run Backwards Compatibility
      run: npm run bw-compatibility
