name: Multi Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the foundation layer
      run: docker build -f ./docker/foundation/Dockerfile -t ghcr.io/browserless/foundation:latest .

    - name: Build the multi image
      run: docker build -f ./docker/multi/Dockerfile -t ghcr.io/browserless/multi:latest .

    - name: Test the multi image
      run: docker run --ipc=host -e CI=true --entrypoint ./test.sh ghcr.io/browserless/multi:latest
