name: Firefox

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the base layer
      run: docker build -f ./docker/base/Dockerfile -t ghcr.io/browserless/base:latest .

    - name: Build the Firefox image
      run: docker build --build-arg VERSION=latest -f ./docker/firefox/Dockerfile -t ghcr.io/browserless/firefox:latest .

    - name: Test the Firefox image
      run: docker run --ipc=host -e CI=true --entrypoint ./test.sh ghcr.io/browserless/firefox:latest
