name: Chromium Latest

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the latest browserless/base image
      run: docker build -t browserless/base:latest base

    - name: Build the latest browserless/chrome image
      run: docker build --build-arg BASE_VERSION=latest -t browserless/chrome:latest .

    - name: Test the latest image
      run: docker run --ipc=host -e CI=true --entrypoint ./test.sh browserless/chrome:latest
