name: Chrome

on: [workflow_call]

jobs:
  Test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Build the base layer
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_wait_seconds: 30
          command: docker build -f ./docker/base/Dockerfile -t ghcr.io/browserless/base:latest .

      - name: Build the Chrome image
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_wait_seconds: 30
          command: docker build --build-arg VERSION=latest -f ./docker/chrome/Dockerfile -t ghcr.io/browserless/chrome:latest .

      - name: Test the Chrome image
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_wait_seconds: 30
          command: docker run --ipc=host -e CI=true --entrypoint ./scripts/test.sh ghcr.io/browserless/chrome:latest
