name: Build Docker Images

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
      
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
      
    - name: DockerHub Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    
    - name: Pre-check
      id: precheck
      run: |
          BUILD_BASE=$(git diff --name-only '$GITHUB_BASE_REF..$GITHUB_SHA' | grep 'base/Dockerfile' | wc -l)
          echo "::set-output name=BUILD_BASE::${BUILD_BASE}" 
          echo "BUILD_BASE: ${BUILD_BASE}"


    - name: Build Base Image
      if: steps.precheck.outputs.BUILD_BASE > 0
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          -t ${{ secrets.DOCKER_USER }}/browserless-base:latest \
          -f ./base/Dockerfile \
          ./base/

    - name: Run Browserless Image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          -t ${{ secrets.DOCKER_USER }}/browserless:latest \
          .
