name: Chromium

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the base layer
      run: docker build -f ./docker/base/Dockerfile -t ghcr.io/browserless/base:latest .

    - name: Build the Chrome image
      run: docker build --build-arg VERSION=latest -f ./docker/chrome/Dockerfile -t ghcr.io/browserless/chrome:latest .

    - name: Test the Chrome image
      run: docker run --ipc=host -e CI=true --entrypoint ./test.sh ghcr.io/browserless/chrome:latest
