name: Build Docker Images

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
      
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
      
    - name: DockerHub Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Build Base Image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          -t badmikko/browserless-base:latest \
          -f ./base/Dockerfile \
          ./base/

    - name: Run Browserless Image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          -t badmikko/browserless:latest \
          .
