name: Leak Check

on: [workflow_call, workflow_dispatch]

permissions:
  contents: read

jobs:
  Leak-Check:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install modules
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_wait_seconds: 30
          command: npm clean-install

      - name: Build
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_wait_seconds: 30
          command: npm run build

      # NOTE it's important to not use npx playwright-core here since it'll likely install
      # a more recent version than we potentially have in our own package.json
      - name: Install Chromium
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_wait_seconds: 30
          command: ./node_modules/playwright-core/cli.js install --with-deps chromium

      - name: Run leak check
        run: node --expose-gc scripts/leak-check.js
        timeout-minutes: 15
