name: Lint

on: [workflow_call]

jobs:
  Lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm clean-install
      - name: Run ESLint
        run: npm run lint
