name: Publish Latest Docker image

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push multi-platform images to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the latest base image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            browserless/base:latest
          context: ./base
          push: true
          platforms: |
            linux/amd64
            linux/arm64

      - name: Build the latest chrome image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BASE_VERSION=latest
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            browserless/chrome:latest
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
