# Ignore non-edge routes
src/routes/chrome
src/routes/chromium
src/routes/firefox
src/routes/webkit

# Build Files
node_modules/
build/

# Editor preferences
.editorconfig
.dockerignore
.git/
.no-git/
.vscode/

# ENV files
*.env*

# Other non-production dotfiles
.eslintrc
